[2025-02-08T02:00:43.998+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T02:00:44.039+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Incident_Report_Generation.procesar_logs_up_down manual__2025-02-08T02:00:17.622550+00:00 [queued]>
[2025-02-08T02:00:44.062+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Incident_Report_Generation.procesar_logs_up_down manual__2025-02-08T02:00:17.622550+00:00 [queued]>
[2025-02-08T02:00:44.079+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-08T02:00:44.121+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): procesar_logs_up_down> on 2025-02-08 02:00:17.622550+00:00
[2025-02-08T02:00:44.160+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=303) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-08T02:00:44.164+0000] {standard_task_runner.py:72} INFO - Started process 309 to run task
[2025-02-08T02:00:44.169+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Incident_Report_Generation', 'procesar_logs_up_down', 'manual__2025-02-08T02:00:17.622550+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/Incident_Report_Generation.py', '--cfg-path', '/tmp/tmptgy9tpxx']
[2025-02-08T02:00:44.170+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask procesar_logs_up_down
[2025-02-08T02:00:44.322+0000] {task_command.py:467} INFO - Running <TaskInstance: Incident_Report_Generation.procesar_logs_up_down manual__2025-02-08T02:00:17.622550+00:00 [running]> on host 0b0ecc2e9e80
[2025-02-08T02:00:44.605+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Incident_Report_Generation' AIRFLOW_CTX_TASK_ID='procesar_logs_up_down' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T02:00:17.622550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T02:00:17.622550+00:00'
[2025-02-08T02:00:44.613+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-08T02:00:44.619+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-08T02:00:44.623+0000] {logging_mixin.py:190} INFO - Current task name:procesar_logs_up_down state:running start_date:2025-02-08 02:00:44.040532+00:00
[2025-02-08T02:00:44.625+0000] {logging_mixin.py:190} INFO - Dag name:Incident_Report_Generation and current dag run status:running
[2025-02-08T02:00:44.630+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T02:00:44.690+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T02:00:44.713+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T02:00:44.736+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Incident_Report_Generation, task_id=procesar_logs_up_down, run_id=manual__2025-02-08T02:00:17.622550+00:00, execution_date=20250208T020017, start_date=20250208T020044, end_date=20250208T020044
[2025-02-08T02:00:44.776+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-08T02:00:44.786+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-08T02:00:44.797+0000] {logging_mixin.py:190} INFO - Dag name:Incident_Report_Generation queued_at:2025-02-08 02:00:18.336138+00:00
[2025-02-08T02:00:44.806+0000] {logging_mixin.py:190} INFO - Task hostname:0b0ecc2e9e80 operator:PythonOperator
[2025-02-08T02:00:44.853+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T02:00:44.899+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T02:00:44.913+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
